# Generated by Django 4.0.1 on 2022-01-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='')),
                ('statut', models.CharField(max_length=10)),
                ('note', models.FloatField(max_length=4)),
            ],
        ),
    ]
