# Generated by Django 4.0.1 on 2022-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomncadreur', models.CharField(max_length=50)),
                ('PrenomEncadreur', models.CharField(max_length=50)),
                ('Telephone', models.IntegerField()),
                ('Mail', models.EmailField(max_length=254)),
                ('grade', models.CharField(max_length=50)),
                ('domaineInteret', models.CharField(max_length=50)),
            ],
        ),
    ]
