# Generated by Django 4.0.1 on 2022-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0002_encadreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeAcceuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomOrganisme', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('RaisonSocial', models.CharField(max_length=50)),
                ('Service', models.CharField(max_length=50)),
                ('Departement', models.CharField(max_length=50)),
            ],
        ),
    ]
