# Generated by Django 4.0.1 on 2022-01-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0003_organismeacceuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FicheDemande', models.FileField(upload_to='')),
                ('idfEncadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.encadreur')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='satgesiV2.stage')),
                ('Type_Stage', models.CharField(max_length=4)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('NbreStagiare', models.IntegerField()),
                ('idfGroupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='satgesiV2.groupestagiaire')),
            ],
            bases=('satgesiV2.stage',),
        ),
        migrations.CreateModel(
            name='Stagiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('NomStagiere', models.CharField(max_length=50)),
                ('PrenomStagiere', models.CharField(max_length=50)),
                ('niveau', models.IntegerField()),
                ('DateNaissance', models.DateField()),
                ('idf_Groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.groupestagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Sinscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeStage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.type')),
                ('idfGroupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.groupestagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='SeDeroule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeStage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.type')),
                ('idfOrganisme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.organismeacceuil')),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPromoteur', models.CharField(max_length=50)),
                ('PrenomPromoteur', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('FonctionOccupée', models.CharField(max_length=50)),
                ('domainIntérêt', models.CharField(max_length=50)),
                ('idfGroupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='satgesiV2.groupestagiaire')),
                ('idfOrganisme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.organismeacceuil')),
            ],
        ),
        migrations.AddField(
            model_name='groupestagiaire',
            name='idfpromoteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.promoteur'),
        ),
    ]
