# Generated by Django 4.0.1 on 2022-01-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0005_alter_promoteur_idfgroupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupestagiaire',
            name='idfEncadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.encadreur'),
        ),
        migrations.AlterField(
            model_name='groupestagiaire',
            name='idfpromoteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.promoteur'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='idfOrganisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.organismeacceuil'),
        ),
        migrations.AlterField(
            model_name='sederoule',
            name='TypeStage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.type'),
        ),
        migrations.AlterField(
            model_name='sinscrit',
            name='idfGroupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.groupestagiaire'),
        ),
        migrations.AlterField(
            model_name='type',
            name='idfGroupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='satgesiV2.groupestagiaire'),
        ),
    ]
