# Generated by Django 4.0.1 on 2022-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0007_alter_promoteur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiere',
            name='niveau',
            field=models.PositiveIntegerField(),
        ),
    ]
