# Generated by Django 4.0.1 on 2022-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0008_alter_stagiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadreur',
            name='Telephone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stagiere',
            name='matricule',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='NbreStagiare',
            field=models.PositiveIntegerField(),
        ),
    ]
