# Generated by Django 4.0.1 on 2022-01-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0010_remove_groupestagiaire_idfencadreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupestagiaire',
            name='idfencadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satgesiV2.encadreur'),
        ),
    ]
