# Generated by Django 3.2.9 on 2022-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0011_groupestagiaire_idfencadreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='anne_univ',
            field=models.DateField(null=True),
        ),
    ]
