# Generated by Django 3.2.9 on 2022-01-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0015_remove_stage_anne_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='anne_univ',
            field=models.DateField(default='2021-08-10'),
            preserve_default=False,
        ),
    ]
