# Generated by Django 3.2.9 on 2022-01-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0020_stage_anne_univ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='anne_univ',
            new_name='anneuniv',
        ),
    ]
