# Generated by Django 4.0.1 on 2022-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0021_rename_anne_univ_stage_anneuniv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupestagiaire',
            name='FicheDemande',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='stage',
            name='document',
            field=models.FileField(upload_to=None),
        ),
    ]
