# Generated by Django 4.0.1 on 2022-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satgesiV2', '0022_alter_groupestagiaire_fichedemande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupestagiaire',
            name='FicheDemande',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
